### ISSUE TITLE
How to run test-api? 

### ISSUE THREAD

**Issue by stensalweb** [LucasMull/concord#1]
I tried your test-api, and got the following message. Do you have any advice of how to debug it? 
```
[src/concord-api-ratelimit.c:289] Concord_bucket_build()
	Bucket key found: /users/%s/guilds
	Attempting to get matching hash ... 
	Couldn't find bucket hash assigned to key, creating new conn ... 
	New conn created
	Conn URL: https://discord.com/api/users/@me/guilds
[src/concord-api.c:470] Concord_register_bucket_key()
	ERROR:	Found not yet implemented HTTP Code: 401
Aborted
```

**Comment by LucasMull** [comment]
Hello, sorry for the late reply! 
You are receiving a code 401 from Discord's end, which means Unauthorized Access. For the the test-api to work properly you should provide it a working bot token, simply create a new file named "bot_token" containing the token, and the test should work.

**Comment by LucasMull** [comment]
Let me know if it fixes your issue

**Comment by stensalweb** [comment]
I created a bot_token with the token.  What permissions are needed for this  test-api?  BTW, I'm interested in contributing and sponsoring your project.

**Comment by stensalweb** [comment]
I recreated a bot and gave it the admin permission, the 401 error is gone. But I got another error.

```
[src/concord-api-ratelimit.c:289] Concord_bucket_build()
	Bucket key found: /users/%s/guilds
	Attempting to get matching hash ... 
	Couldn't find bucket hash assigned to key, creating new conn ... 
	New conn created
	Conn URL: https://discord.com/api/users/@me/guilds
	Object loaded with API response
	New Key/Hash pair:  /users/%s/guilds - 2a0617accf8bb8625c43e2ffeb5b8d5b
[src/concord-api-ratelimit.c:272] Concord_trycreate_bucket()
	Bucket hash not found, creating new bucket ...
	Appending new bucket to clients bucket at slot 0
	Created Bucket
	No transfers on hold, returning ...
[src/concord-api-ratelimit.c:289] Concord_bucket_build()
	Bucket key found: guild_major
	Attempting to get matching hash ... 
	Couldn't find bucket hash assigned to key, creating new conn ... 
	New conn created
	Conn URL: https://discord.com/api/guilds/562694099887587338
	Object loaded with API response
	New Key/Hash pair:  guild_major - 2a0617accf8bb8625c43e2ffeb5b8d5b
[src/concord-api-ratelimit.c:289] Concord_bucket_build()
	Bucket key found: guild_major
	Attempting to get matching hash ... 
	Matching hash found: 2a0617accf8bb8625c43e2ffeb5b8d5b
	Recycling INNACTIVE connection at queue's slot 0
[src/concord-api-ratelimit.c:195] Concord_queue_npop()
	Adding conns:	1
	Bucket Hash:	2a0617accf8bb8625c43e2ffeb5b8d5b
	Queue Size:	15
	Queue Bottom:	0
	Queue Separator:1
	Queue Top:	1
	Creating new context
[src/concord-common.c:22] Concord_context_init()
	ERROR:	Assert Failed:	Unknown system error -115
	Expected:	!uvcode
Aborted
```

**Comment by LucasMull** [comment]
> I created a bot_token with the token.  But I got the same error. What permissions are needed for this  test-api?  BTW, I'm interested in contributing and sponsoring your project.   Do you mind sharing your long term goal for this project? Why do you want to build a discord lib in C?   What is the justification? 

Certainly! The idea came out of sheer frustration from the lack of good and accessible libraries made in C, and also because it seemed like a great learning opportunity. This library is built with asynchronous IO in mind, allowing for a much greater speed than other libraries that deals with requests in synchronous fashion, it also includes discord compliant ratelimiting.

The long term goal is to cover the API in its entirety but as it stands today it still lacks much of the critical stuff, which is pretty much the backbone that need to be implemented before moving on covering API specific functions.

On regard to contributing and sponsoring this project, you can get in touch with me on my discord (müller#5436) so that we may discuss some details, I'm still pretty clueless when it comes to that kind of thing.

**Comment by LucasMull** [comment]
> I recreated a bot and gave it the admin permission, the 401 error is gone. But I got another error.
> 
> 
> 
> ```
> 
> [src/concord-api-ratelimit.c:289] Concord_bucket_build()
> 
> 	Bucket key found: /users/%s/guilds
> 
> 	Attempting to get matching hash ... 
> 
> 	Couldn't find bucket hash assigned to key, creating new conn ... 
> 
> 	New conn created
> 
> 	Conn URL: https://discord.com/api/users/@me/guilds
> 
> 	Object loaded with API response
> 
> 	New Key/Hash pair:  /users/%s/guilds - 2a0617accf8bb8625c43e2ffeb5b8d5b
> 
> [src/concord-api-ratelimit.c:272] Concord_trycreate_bucket()
> 
> 	Bucket hash not found, creating new bucket ...
> 
> 	Appending new bucket to clients bucket at slot 0
> 
> 	Created Bucket
> 
> 	No transfers on hold, returning ...
> 
> [src/concord-api-ratelimit.c:289] Concord_bucket_build()
> 
> 	Bucket key found: guild_major
> 
> 	Attempting to get matching hash ... 
> 
> 	Couldn't find bucket hash assigned to key, creating new conn ... 
> 
> 	New conn created
> 
> 	Conn URL: https://discord.com/api/guilds/562694099887587338
> 
> 	Object loaded with API response
> 
> 	New Key/Hash pair:  guild_major - 2a0617accf8bb8625c43e2ffeb5b8d5b
> 
> [src/concord-api-ratelimit.c:289] Concord_bucket_build()
> 
> 	Bucket key found: guild_major
> 
> 	Attempting to get matching hash ... 
> 
> 	Matching hash found: 2a0617accf8bb8625c43e2ffeb5b8d5b
> 
> 	Recycling INNACTIVE connection at queue's slot 0
> 
> [src/concord-api-ratelimit.c:195] Concord_queue_npop()
> 
> 	Adding conns:	1
> 
> 	Bucket Hash:	2a0617accf8bb8625c43e2ffeb5b8d5b
> 
> 	Queue Size:	15
> 
> 	Queue Bottom:	0
> 
> 	Queue Separator:1
> 
> 	Queue Top:	1
> 
> 	Creating new context
> 
> [src/concord-common.c:22] Concord_context_init()
> 
> 	ERROR:	Assert Failed:	Unknown system error -115
> 
> 	Expected:	!uvcode
> 
> Aborted
> 
> ```

Can you tell me which system you tried to run the test on (I've tested it exclusively on Linux Mint)? Its a libuv error, that is begin triggered when trying to unsuccesfully create a epoll socket, though it needs more investigating.

**Comment by stensalweb** [comment]
I build libuv from the latest source code. The following is my OS info. 

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie
```

**Comment by stensalweb** [comment]
> müller#5436
this is an invite for my server: https://discord.gg/mkG9Ayn7
Once you join, please DM me (@garth).

**Comment by LucasMull** [comment]
> I built libuv from the latest source code. The following is my OS info.
> 
> ```
> No LSB modules are available.
> Distributor ID:	Debian
> Description:	Debian GNU/Linux 8.9 (jessie)
> Release:	8.9
> Codename:	jessie
> ```

Hey, so I went on a little digging and found that you are receiving a system error 115 (EINPROGRESS). I could not replicate the error on my system but it's related to epoll attempting to connect a non-blocking socket. The following is from the connect man page: "[EINPROGRESS] The socket is non-blocking and the connection cannot be completed immediately."

I'll do some more research and look how to circumvent this issue! In the meantime, try running libuv's test suite and see if you end up having the same issue there.

**Comment by stensalweb** [comment]
I ran the test came with libuv, it passed on my system.  the invite link might have expired, I sent you a DM.

**Comment by LucasMull** [comment]
Since I will no longer be working in this library in favor to [orca](https://github.com/cee-studio/orca), I'll be closing this now. I learned a lot from this implementation, and I'm glad it served its purpose.
